
package Front;

import Back.Cargar;
import javax.swing.ImageIcon;

/** 
 * <b>CLASE:</b> Logo.java 
 * <b>OBJETIVO:</b> Proporcional el logo de la interfaz usurio..
 * 
 *							
 * ASIGNATURA o PROYECTO: 	Proyecto integrador.
 *
 * 
 * @version 1.1 30/11/2023 
 * @author Juan Diaz 
 */
public final class Logo extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    
    Cargar hilo;
    
    public Logo() {
        
        // Set the title and icon for the JFrame.
        setTitle("--ELECTRONE PRADASHA--");
        setIconImage(new ImageIcon(getClass().getResource("/Img/boss.png")).getImage());
        initComponents();
          iniciar();
        
    }
    
    /** 
     * <b>iniciar()</b>
     * <b>OBJETIVO:</b>mostrar con un hilo la barra de carga.
     * 
     * 
     */
   public void iniciar(){
        setLocationRelativeTo(null);
        getProgreso().setVisible(true);
        hilo=new Cargar(getProgreso());
        hilo.start();
        hilo=null;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Progreso = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Progreso.setBackground(new java.awt.Color(153, 153, 153));
        Progreso.setForeground(new java.awt.Color(0, 102, 102));
        Progreso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ProgresoStateChanged(evt);
            }
        });
        getContentPane().add(Progreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 720, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondoep.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1060, 640));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProgresoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ProgresoStateChanged
        // TODO add your handling code here:
         if(Progreso.getValue()==100){
        /*if(j!=101){
            AWTUtilities.setWindowOpacity(this, Float.valueOf((100-j)/100+"f"));
            i++;
            j+=2;
        }*/
       System.out.println("\nIniciar sesion\n");
        Login iniciar = new Login();
                        iniciar.setVisible(true);
                        dispose();
        
         
    }
   /* if(Progreso.getValue()==100){
        ventana2 v=new ventana2();
        v.setVisible(true);
        this.dispose();
    }*/
    }//GEN-LAST:event_ProgresoStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
   /**
     * @return the Progreso
     */
    public javax.swing.JProgressBar getProgreso() {
        return Progreso;
    }

    /**
     * @param Progreso the Progreso to set
     */
    public void setProgreso(javax.swing.JProgressBar Progreso) {
        this.Progreso = Progreso;
    }


}//fin clase Logo
